name: PHP Lint

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        git submodule update --init --recursive
        composer install
    - name: PHP Lint
      run: |
        php ./lint.php
